# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. For example:

In [3]:
import numpy as np
arr = np.arange(0,10)

In [4]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### usually when an element is divided by zero, zero division error pops up! 
 

In [8]:
1/0

ZeroDivisionError: division by zero

### But in Numpy it throws Warning on division by zero, but not an error!
### the element gets replaced with nan

In [10]:
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
arr/0

array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [12]:
# Also warning, but not an error instead infinity
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.

In [13]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [15]:
#Calcualting log
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# For more details refer the array functions!