# NumPy Indexing and Selection
selecting elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
arr[1]

1

In [5]:
arr[8]

8

In [6]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#Get values in a range
arr[1:6]

array([1, 2, 3, 4, 5])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [9]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_arr[:]=100

In [13]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

Now note the changes also occur in our original array!

In [14]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [15]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

now if we change in the new array `arr_copy` the changes wont be occured in the original array!

In [17]:
arr_copy[0:3]=300

In [18]:
arr_copy

array([300, 300, 300, 100, 100, 100,   6,   7,   8,   9,  10])

In [19]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

as we can see the number 300 has not been changed in the original array!

## Indexing a 2D array (matrices)

The general format is **arr_2d [row][col]** or **arr_2d [row,col]**. 

In [20]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [22]:
#indexing a number
arr_2d[0][1]

10

In [23]:
#indexing the same element by using single square brackets!
arr_2d[0,1]

10

In [24]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order

In [25]:
#Set up matrix
arr2d = np.zeros((10,10))

In [32]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10

In [33]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [34]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [35]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [36]:
arr.shape

(11,)

In [43]:
arr=np.delete(arr,-1)
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [49]:
arr=arr.reshape(5,2)
arr

array([[100, 100],
       [100, 100],
       [100, 100],
       [  6,   7],
       [  8,   9]])

In [50]:
arr[[4,1,3]]

array([[  8,   9],
       [100, 100],
       [  6,   7]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [51]:
array = np.arange(1,11)

In [52]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
array>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
bool_arr = array>5

In [55]:
#display elements greater than 5!
array[bool_arr]

array([ 6,  7,  8,  9, 10])

In [56]:
# or we can do like this too
array[array>5]

array([ 6,  7,  8,  9, 10])