In [1]:
import numpy as np

## Creating A List 

In [2]:
one_dimensional = [1,2,3]
two_dimensional = [[1,2,3],[4,5,6],[7,8,9]]

## Creating An Array From Python List

In [8]:
a=np.array(one_dimensional)
a

array([1, 2, 3])

In [9]:
b=np.array(two_dimensional)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### To check the dimensions

In [10]:
a.ndim

1

In [11]:
b.ndim

2

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [15]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [16]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

## eye

Creates an identity matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [20]:
np.random.rand(2)

array([0.10069946, 0.13911469])

In [21]:
np.random.rand(4)

array([0.1863929 , 0.12280066, 0.42262089, 0.49060203])

In [23]:
np.random.rand(4,4)

array([[0.5810715 , 0.69449447, 0.45910165, 0.12099339],
       [0.79247414, 0.21209948, 0.10137579, 0.77293781],
       [0.68736848, 0.11482465, 0.13863448, 0.83973251],
       [0.80557691, 0.8457568 , 0.01649731, 0.91727254]])

In [24]:
np.random.rand(2,3)

array([[0.51394544, 0.29544975, 0.20168272],
       [0.29256001, 0.33205807, 0.7175299 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [25]:
np.random.randn(3)

array([-0.02488019,  0.00663952, -0.10872531])

In [26]:
np.random.randn(3,3)

array([[-0.63704279,  0.94462567,  0.06455995],
       [-0.02557907, -0.36661952, -0.46173388],
       [ 0.45159666,  0.69711787, -0.20544435]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [27]:
np.random.randint(0,2)

1

In [29]:
np.random.randint(0,15)

5

In [30]:
np.random.randint(1,20,6)

array([18, 15,  6, 14, 12, 11])

### random

In [5]:
# Random array !Note the size converts the 1D array to 2D array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[6, 5, 7],
       [3, 2, 4],
       [7, 3, 4],
       [6, 6, 9],
       [4, 0, 7]])

In [8]:
# Random array of floats (between 0 & 1)
np.random.random((5,3))

array([[0.00443769, 0.47927868, 0.80434738],
       [0.4639679 , 0.40144232, 0.31369458],
       [0.71950013, 0.32334559, 0.81454805],
       [0.24883037, 0.17909363, 0.67301034],
       [0.71846856, 0.51177959, 0.34568034]])

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.

For consistency, you might want to keep the random numbers you generate similar throughout experiments.

To do this, you can use np.random.seed().

What this does is it tells NumPy, "Hey, I want you to create random numbers but keep them aligned with the seed."

## Array Attributes and Methods

Some useful attributes and methods or an array:

In [32]:
array = np.arange(30)
random_array = np.random.randint(0,30,15)

In [33]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
random_array

array([21, 12, 18, 20,  0, 12, 23,  3, 13, 21, 17, 15, 20,  2,  9])

## Reshape
Returns an array containing the same data with a new shape.

In [35]:
array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [38]:
array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [39]:
random_array

array([21, 12, 18, 20,  0, 12, 23,  3, 13, 21, 17, 15, 20,  2,  9])

In [41]:
random_array.max()

23

In [43]:
#max element index location
random_array.argmax()

6

In [44]:
random_array.min()

0

In [45]:
random_array.argmax()

6

## Shape

Shape is an attribute that arrays have (not a method):

In [46]:
array.shape

(30,)

In [48]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
arr.shape

(2, 4)

In [50]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
#reshaping the array to 2D
array.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [55]:
reshaped_array_2D=array.reshape(2,15)
reshaped_array_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])